### ISSUE TITLE
Crashes on startup, Fiskarsinjoki

### ISSUE THREAD

**Issue by enshat** [QtGram/harbour-sailorgram#100] opened 2016-10-19 21:55 UTC
Version harbour-sailorgram-0.80-2, affected SailfishOS 2.0.4.13-14.
I have one secret chat and several standard. There was no stickers in secret chat.
Started to crash on startup recently. Please let me know if you need any additional debug or log lines.

Thanks.

Error log:

```
[D] InboundPkt::fetchInt:92 - fetchInt() 467867529  ( "0x1be31789" ) 
[D] InboundPkt::fetchStr:128 - fetchStr(), len = 15 
[D] InboundPkt::fetchInt:92 - fetchInt() 29  ( "0x1d" ) 
[D] InboundPkt::fetchInt:92 - fetchInt() 4  ( "0x4" ) 
[D] InboundPkt::fetchInt:92 - fetchInt() 7  ( "0x7" ) 
[D] Decrypter::decryptEncryptedData:99 - Received in_seq_no= 4 (expected 6 ) 
[D] Decrypter::decryptEncryptedData:100 - Received out_seq_no= 7 (expected 11 ) 
[W] Decrypter::decryptEncryptedData:115 - Received out_seq_no ( 3 ) is lower than expected ( 5 ) 
[D] InboundPkt::fetchInt:92 - fetchInt() 541931640  ( "0x204d3878" ) 
[D] InboundPkt::fetchLong:106 - fetchLong() -8177484411033251071 
[D] InboundPkt::fetchInt:92 - fetchInt() 0  ( "0x0" ) 
[D] InboundPkt::fetchStr:128 - fetchStr(), len = 124 
[D] InboundPkt::fetchInt:92 - fetchInt() 144661578  ( "0x89f5c4a" ) 
[D] InboundPkt::fetchLong:106 - fetchLong() -2318129074813232213 
[D] Decrypter::checkKeyFingerprints:186 - Received keyFingerprint -2318129074813232213 
[D] Decrypter::checkKeyFingerprints:187 - Stored keyFingerprint -2318129074813232213 
[D] Decrypter::checkKeyFingerprints:191 - keyFingerprints matches!! 
[D] Decrypter::decryptEncryptedMessage:256 - SHA1 checked and valid 
[D] InboundPkt::fetchInt:92 - fetchInt() 256  ( "0x100" ) 
[D] Decrypter::decryptEncryptedMessage:260 - decrypted data length 256 
[D] InboundPkt::fetchInt:92 - fetchInt() 467867529  ( "0x1be31789" ) 
[D] InboundPkt::fetchStr:128 - fetchStr(), len = 15 
[D] InboundPkt::fetchInt:92 - fetchInt() 29  ( "0x1d" ) 
[D] InboundPkt::fetchInt:92 - fetchInt() 6  ( "0x6" ) 
[D] InboundPkt::fetchInt:92 - fetchInt() 9  ( "0x9" ) 
[D] Decrypter::decryptEncryptedData:99 - Received in_seq_no= 6 (expected 6 ) 
[D] Decrypter::decryptEncryptedData:100 - Received out_seq_no= 9 (expected 11 ) 
[W] Decrypter::decryptEncryptedData:115 - Received out_seq_no ( 4 ) is lower than expected ( 5 ) 
[D] InboundPkt::fetchInt:92 - fetchInt() 541931640  ( "0x204d3878" ) 
[D] InboundPkt::fetchLong:106 - fetchLong() 6275965600493936698 
[D] InboundPkt::fetchInt:92 - fetchInt() 0  ( "0x0" ) 
[D] InboundPkt::fetchStr:128 - fetchStr(), len = 202 
[D] InboundPkt::fetchInt:92 - fetchInt() 144661578  ( "0x89f5c4a" ) 
[D] InboundPkt::fetchLong:106 - fetchLong() -2318129074813232213 
[D] Decrypter::checkKeyFingerprints:186 - Received keyFingerprint -2318129074813232213 
[D] Decrypter::checkKeyFingerprints:187 - Stored keyFingerprint -2318129074813232213 
[D] Decrypter::checkKeyFingerprints:191 - keyFingerprints matches!! 
[D] Decrypter::decryptEncryptedMessage:256 - SHA1 checked and valid 
[D] InboundPkt::fetchInt:92 - fetchInt() 316  ( "0x13c" ) 
[D] Decrypter::decryptEncryptedMessage:260 - decrypted data length 316 
[D] InboundPkt::fetchInt:92 - fetchInt() 467867529  ( "0x1be31789" ) 
[D] InboundPkt::fetchStr:128 - fetchStr(), len = 15 
[D] InboundPkt::fetchInt:92 - fetchInt() 29  ( "0x1d" ) 
[D] InboundPkt::fetchInt:92 - fetchInt() 6  ( "0x6" ) 
[D] InboundPkt::fetchInt:92 - fetchInt() 11  ( "0xb" ) 
[D] Decrypter::decryptEncryptedData:99 - Received in_seq_no= 6 (expected 6 ) 
[D] Decrypter::decryptEncryptedData:100 - Received out_seq_no= 11 (expected 11 ) 
[D] Decrypter::decryptEncryptedData:136 - Updating in_seq_no; Current values -> out_seq_no: 4 ,in_seq_no: 6 
[D] InboundPkt::fetchInt:92 - fetchInt() 1930838368  ( "0x73164160" ) 
[D] InboundPkt::fetchLong:106 - fetchLong() 1358629648789098849 
[D] InboundPkt::fetchInt:92 - fetchInt() -204906213  ( "0xf3c9611b" ) 
[F] qt_assert:2096 - ASSERT: "x == (qint32)DecryptedMessageAction::typeDecryptedMessageActionSetMessageTTL || x == (qint32)DecryptedMessageAction::typeDecryptedMessageActionReadMessages || x == (qint32)DecryptedMessageAction::typeDecryptedMessageActionDeleteMessages || x == (qint32)DecryptedMessageAction::typeDecryptedMessageActionScreenshotMessages || x == (qint32)DecryptedMessageAction::typeDecryptedMessageActionFlushHistory || x == (qint32)DecryptedMessageAction::typeDecryptedMessageActionResend || x == (qint32)DecryptedMessageAction::typeDecryptedMessageActionNotifyLayer || x == (qint32)DecryptedMessageAction::typeDecryptedMessageActionTyping" in file ../../SailorGram/libqtelegram-aseman-edition/secret/decrypter.cpp, line 424
Aborted

```

**Comment by Dax89** [comment] 2016-10-20 07:54
Duplicate of https://github.com/QtGram/harbour-sailorgram/issues/10

Reset the client by deleting the folder "harbour-sailorgram" located in /home/nemo/.local/share and do not use secret chats until I release the 0.9, currently it makes the client unstable

**Closed by Dax89** 2016-10-20 07:54 UTC

**Comment by enshat** [comment] 2016-10-20 12:52
Thank you for the update. I'll wait the 0.9 release.
