### ISSUE TITLE
[0.89-10] Sharing pictures freezes

### ISSUE THREAD

**Issue by TomiOhl** [QtGram/harbour-sailorgram#103] opened 2016-11-18 10:07 UTC
Sailfish OS 2.0.1.11 on Xperia mini pro. When I click on sharing icon, the file chooser UI comes in, but the app is not responding anymore.
Is this a common issue, or it's just happening to me?
Apart from this, I haven't found any bugs in my short testing time. Keep it up! ☺️

**Comment by Nokius** [comment] 2016-11-18 11:49
I tried to reproduce it on the Jolla C which was not happening. iirc the RAM on the Xperia is 512MB and the port use zswap may the thumbnail generation is taking a lot of RAM :s

**Comment by Dax89** [comment] 2016-11-18 11:57
I have multiple report on this, but I have managed to reproduce this issue only one time.

**Comment by TomiOhl** [comment] 2016-11-18 12:00
Thanks for the reply. So it seems like it's a RAM issue? Nevermind, I've just quickly tried it out on Xperia which I'm not using as daily driver. As all Jolla phones have more RAM, this issue isn't very important I guess.

**Comment by Dax89** [comment] 2016-11-18 12:03
No, it seems some kind of qml infinite recursion/loop, because I can see the library events in the log

**Comment by Dax89** [comment] 2016-11-18 12:04
@Nokius: I have reproduced this issue in the file picker, which doesn't generates thumbnails :D

**Comment by Dax89** [comment] 2016-11-18 12:12
Ok, I can reproduce now:

1. Open the file picker in portrait
2. Rotate the phone in order to change the orientation to landspace
3. Change it back to portrait
4. Freeze

**Comment by Nokius** [comment] 2016-11-18 12:37
yeap I can conform it :)

**Comment by Nokius** [comment] 2016-11-18 12:40
I also just got the issue @TomiOhl was describing

1. press on type area
2. keyboard pops up
3. press file picker
4. file picker opens
5. Freeze 
done on the JollaC

**Comment by Dax89** [comment] 2016-11-18 12:41
It's an unhandled binding loop with Silica's DockedPanel.
It should be never used for height calculation or the qml engine goes crazy.

Fix is coming :)

**Comment by Dax89** [comment] 2016-11-18 13:06
Fixed in https://github.com/QtGram/harbour-sailorgram/commit/c08dcfc966a22cd8346c23dc717ee6a6677b64f0

**Closed by Dax89** 2016-11-18 13:06 UTC
Labels: beta, bug, important

**Comment by TomiOhl** [comment] 2016-11-18 13:14
This was fast! Thanks!
